// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3lcbQqedpYkXXGiDHfUCTZCkKg__QGI',
    appId: '1:1042923450038:web:f3aa74bf704dbd01f94017',
    messagingSenderId: '1042923450038',
    projectId: 'mathbot-570d7',
    authDomain: 'mathbot-570d7.firebaseapp.com',
    databaseURL: 'https://mathbot-570d7-default-rtdb.firebaseio.com',
    storageBucket: 'mathbot-570d7.appspot.com',
    measurementId: 'G-MNTKG36R6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwSVKD82XbZDRMxEN17iTXC0q_1m29HG0',
    appId: '1:1042923450038:android:bf9900d2439874aff94017',
    messagingSenderId: '1042923450038',
    projectId: 'mathbot-570d7',
    databaseURL: 'https://mathbot-570d7-default-rtdb.firebaseio.com',
    storageBucket: 'mathbot-570d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ti_h8M-6MJUjlz6bpOUw3wnTqOI3C3A',
    appId: '1:1042923450038:ios:e652dc90eebc9ad6f94017',
    messagingSenderId: '1042923450038',
    projectId: 'mathbot-570d7',
    databaseURL: 'https://mathbot-570d7-default-rtdb.firebaseio.com',
    storageBucket: 'mathbot-570d7.appspot.com',
    iosClientId: '1042923450038-iuhdc8h9bi5cpdcl5ia6cveafdqq9qds.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ti_h8M-6MJUjlz6bpOUw3wnTqOI3C3A',
    appId: '1:1042923450038:ios:e652dc90eebc9ad6f94017',
    messagingSenderId: '1042923450038',
    projectId: 'mathbot-570d7',
    databaseURL: 'https://mathbot-570d7-default-rtdb.firebaseio.com',
    storageBucket: 'mathbot-570d7.appspot.com',
    iosClientId: '1042923450038-iuhdc8h9bi5cpdcl5ia6cveafdqq9qds.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathbot',
  );
}
